// Copyright Epic Games, Inc. All Rights Reserved.

#include "PrologueCharacter.h"
#include "Engine/LocalPlayer.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/Controller.h"
#include "Prologue/PrologueGameplayTags.h"
#include "AbilitySystemComponent.h"
#include "MotionWarpingComponent.h"
#include "Prologue/Component/InputBufferComponent.h"

DEFINE_LOG_CATEGORY(LogTemplateCharacter);

//////////////////////////////////////////////////////////////////////////
// APrologueCharacter

APrologueCharacter::APrologueCharacter()
{
	PrimaryActorTick.bCanEverTick = false;
	PrimaryActorTick.bStartWithTickEnabled = false;

	MotionWarpingComponent = CreateDefaultSubobject<UMotionWarpingComponent>(TEXT("MotionWarpingComponent"));

	GetMesh()->bReceivesDecals = false;

	GetCharacterMovement()->bCanWalkOffLedges = false;
}

UPawnCombatComponent* APrologueCharacter::GetPawnCombatComponent() const
{
	return nullptr;
}

void APrologueCharacter::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);
}

void APrologueCharacter::BeginPlay()
{
	Super::BeginPlay();

	if (ASC && IsValid(this))
	{
		// ŪÉúÍ∑ł žąėžč† ŽĆÄÍłį
		ToughnessTagHandle = ASC->RegisterGameplayTagEvent(PrologueGameplayTags::Shared_State_IsOutOfToughness, EGameplayTagEventType::NewOrRemoved).AddUObject(this, &APrologueCharacter::OnToughnessTagChanged);
	}
}

void APrologueCharacter::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	if (ASC && ToughnessTagHandle.IsValid())
	{
		ASC->UnregisterGameplayTagEvent(ToughnessTagHandle, PrologueGameplayTags::Shared_State_IsOutOfToughness, EGameplayTagEventType::NewOrRemoved);
		ToughnessTagHandle.Reset();
	}
	
	Super::EndPlay(EndPlayReason);
}

// ÍįēžĚłŽŹĄÍįÄ 0žĚī ŽźėžóąžĚĄ ŽēĆ žč§ŪĖČŽźėŽäĒ Ūē®žąė
void APrologueCharacter::OnToughnessTagChanged(const FGameplayTag CallbackTag, int32 NewCount)
{
	if (NewCount > 0)
	{
		LOG_SCREEN_R("Toughness Broken, Applying HitReact");

		if (HitReactEffectClass && ASC)
		{
			// HitReactEffectClassŽ•ľ ŪÜĶŪēīžĄú HitReact AbilityŽ•ľ TriggeržčúŪāī
			FGameplayEffectContextHandle ContextHandle = ASC->MakeEffectContext();
			ContextHandle.AddSourceObject(this);

			FGameplayEffectSpecHandle SpecHandle = ASC->MakeOutgoingSpec(HitReactEffectClass, 1.0f, ContextHandle);
			ASC->ApplyGameplayEffectSpecToSelf(*SpecHandle.Data.Get());
		}

		// 1žīąžĚė ŽĒúŽ†ąžĚīŽ•ľ ž£ľÍ≥† Shared_State_IsOutOfToughness ŪÉúÍ∑ł ž†úÍĪį
		GetWorld()->GetTimerManager().SetTimer(ToughnessRecoveryTimerHandle, this, &APrologueCharacter::RecoverToughness, 1.0f, false);
	}
}

void APrologueCharacter::RecoverToughness()
{
	if (ASC)
	{
		ASC->RemoveLooseGameplayTag(PrologueGameplayTags::Shared_State_IsOutOfToughness);
	}
}

void APrologueCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
}

void APrologueCharacter::InputGAS(const FGameplayTag Tag)
{
	FGameplayTagContainer GameplayTags;

	LOG_SCREEN("%s", *Tag.ToString());
	
	GameplayTags.AddTag(Tag);
	if (ASC)
	{
		// žļĒžä¨ ÍįÄŽä• žĖīŽĻĆŽ¶¨Ūčį
		static TArray<FGameplayTag> CancelableTags = {
			FGameplayTag::RequestGameplayTag(FName("Comma.Ability.Dash")),
			FGameplayTag::RequestGameplayTag(FName("Comma.Ability.Skill")),
			FGameplayTag::RequestGameplayTag(FName("Comma.Ability.Heal"))
		};

		// žĄ†žěÖŽ†•žóźžĄú ž†úžôłžčúŪā¨ žĖīŽĻĆŽ¶¨Ūčį
		static TArray<FGameplayTag> NonBufferTags = {
			FGameplayTag::RequestGameplayTag(FName("Comma.Ability.Attack.Sword")),
			FGameplayTag::RequestGameplayTag(FName("Comma.Ability.Attack.Bow")),
			FGameplayTag::RequestGameplayTag(FName("Comma.Ability.Heal"))
		};

		bool bShouldBuffer = !NonBufferTags.Contains(Tag);

		bool bCanCancel = CancelableTags.Contains(Tag) && ASC->HasMatchingGameplayTag(PrologueGameplayTags::Comma_State_CancelEnabled);

		// NonBufferTagsžĚīÍ≥† žļĒžä¨ ÍįÄŽä•Ūēú žĖīŽĻĆŽ¶¨ŪčįÍįÄ žēĄŽčź ŽēĆžóźŽßĆ žĄ†žěÖŽ†• Žįįžóīžóź ž†Äžě•
		if (bShouldBuffer && ASC->HasMatchingGameplayTag(PrologueGameplayTags::Shared_State_IsAttacking) && !bCanCancel)
		{
			InputBufferComponent->BufferInput(Tag);
			return;
		}
		
		TArray<FGameplayAbilitySpec*> AbilitiesToActivatePtrs;
		ASC->GetActivatableGameplayAbilitySpecsByAllMatchingTags(GameplayTags, AbilitiesToActivatePtrs);
		if (AbilitiesToActivatePtrs.Num() < 1)
		{
			LOG_SCREEN("No Ability Specifications Found");
			return;
		}
		
		TArray<FGameplayAbilitySpec> AbilitiesToActivate;
		AbilitiesToActivate.Reserve(AbilitiesToActivatePtrs.Num());
		Algo::Transform(AbilitiesToActivatePtrs, AbilitiesToActivate, [](FGameplayAbilitySpec* SpecPtr) { return *SpecPtr; });
		
		for (FGameplayAbilitySpec& GameplayAbilitySpec : AbilitiesToActivate)
		{
			ensure(IsValid(GameplayAbilitySpec.Ability));
			if (GameplayAbilitySpec.IsActive())
			{
				ASC->AbilitySpecInputPressed(GameplayAbilitySpec);
			}
			else
			{
				ASC->TryActivateAbility(GameplayAbilitySpec.Handle);
			}
		}
	}
}

UAbilitySystemComponent* APrologueCharacter::GetAbilitySystemComponent() const
{
	return ASC;
}
